### ISSUE TITLE
demo.clj in project root is outdated

### ISSUE THREAD

**Issue by pangloss** [sicmutils/sicmutils#263]
I just tried to load up that file but it doesn't work. Not surprising since it hasn't been edited in 4 years. Probably just needs to be deleted?

**Comment by sritchie** [comment]
Interesting, @pangloss what did you try, and what did you see? When I run

```
lein repl < demo.clj
```

I see a stream of the forms in `demo.clj` interspersed with their outputs, no errors.

However! You're absolutely right that if you try to run these forms outside of `lein repl`, the process can't tell where everything is coming from. I added a namespace form with proper imports in #264 to solve this. Mind giving it a try again?

Thanks for checking out the SICMUtils project!

**Comment by pangloss** [comment]
I checked out the project, opened the file in emacs+cider, did cider-jack-in and tried to eval the buffer. It seemed like a reasonable place to start :)

Your update fixes it, so I'll close this. Thanks this project looks truly incredible, and the materials you guys are building around it are just as good.

**Comment by sritchie** [comment]
Oh, yeah, that is exactly what I tried to reproduce the issue and immediately hit a slew of errors :) I'm glad you found tracked this down.

Thanks for the kind words, and for the bug report! Please keep them coming, and feel free to ask questions via https://github.com/sicmutils/sicmutils/discussions or anywhere else that's convenient.
