### ISSUE TITLE
nextjournal rendering of linear-interpolants

### ISSUE THREAD

**Issue by keesterbrugge** [sicmutils/sicmutils#336]
Hi Sam,

In nextjournal I wanted to explore the functions used in the beginning of chapter 1 bit by bit. expected the output of `linear-interpolants` to be a list of ratio's and understandable as such, but I got the following
![Screenshot from 2021-03-23 18-22-00](https://user-images.githubusercontent.com/6086439/112189917-cb176d00-8c04-11eb-8229-c57ed6806dec.png)

I tried `render` but it is not available in the clojurescript nextjournal environment.

**Comment by sritchie** [comment]
cc @mk 

Looks like we need to bite the bullet and write a nextjournal renderer for ratios! @keesterbrugge we're on it.

**Comment by mk** [comment]
@keesterbrugge @sritchie sorry, just getting around to this now.

What's needed here? I've rebased https://github.com/nextjournal/nextjournal/compare/master...viewer/bigint which at least make our viewers support `js/BigInt` but it looks like we also need to expose `sicmutils.ratio` from `sicmutils.env.sci` is that correct?

**Comment by mk** [comment]
Nevermind, I think I figured it, will push tomorrow.

**Comment by mk** [comment]
@sritchie opened a nextjournal PR for you to review, it's not perfect but better than before:
<img width="1035" alt="Screen Shot 2021-04-02 at 10 30 33" src="https://user-images.githubusercontent.com/1187/113399638-d30fa380-93a0-11eb-908c-ac9aff0aec08.png">

**Comment by mk** [comment]
@sritchie thanks for the review! I just deployed the PR so you should (after a reload) see what I posted above and you can close this issue.

**Comment by sritchie** [comment]
Thank you @mk!
