### ISSUE TITLE
How to use indexed sets

### ISSUE THREAD

**Issue by dylanede** [sicmutils/sicmutils#359]
I'm not sure how best to go about representing an indexed set of objects. My particular use case is that I want to represent a dynamical system of N particles, for some unknown N. I figure that I must use some combination of `literal-function` and the tools in `calculus.indexed`. At first I wanted to create a `literal-function` with the natural numbers as the type of its first argument, but it seems that only `'Real` or product sets built from reals are supported there?

**Comment by sritchie** [comment]
@dylanede, apologies for my big delay here! When you sent this I was in the middle of a big coding push and let comms drop by the wayside.

I'm happy to help here to the extent that I can, if this is still a project you're working on. Can you give me some more information? The tooling in indexed is still mysterious to me, as it is a fairly direct port from Scheme, vs a properly absorbed batch of code filtered through my brain and squeezed out with documentation attached.

**Comment by sritchie** [comment]
@dylanede , closing this for now, feel free to re-open when you have some time. #262 is a project aimed at expanding the literal function descriptor language, which might help.
