### ISSUE TITLE
->infix isn't properly handling exponents.

### ISSUE THREAD

**Issue by sigmaxipi** [sicmutils/sicmutils#373]
`/demo/src/demo/minimal.cljs` uses `(expt sin 2)`. For dev builds, `->infix` properly renders `sin²(x)`. But for `:advanced` builds, `sin°(x)` is shown. This happens with both the advanced CLJS builds and advanced shadow-cljs.

**Comment by sritchie** [comment]
Weird that this wasn't happening on NON-advanced builds! The fix was to add

```
    <head>
        <meta charset="utf-8">
    </head>
```

to the HTML, to force the unicode to display properly.
