### ISSUE TITLE
util.permute functions encounter integer overflows

### ISSUE THREAD

**Issue by swapneils** [sicmutils/sicmutils#441]
Hello. I have been playing around with your library, as it seems a very useful general-purpose mathematical tool for Clojure.

When I tried `(factorial 1000)`, I ran into an ArithmeticException with description "Integer Overflow". A similar event happened with `(sicmutils.util.permute/number-of-combinations 100000000 290)`, which I tried next. 

From the stack trace, I would guess that the file is using the `clojure.core/*` function rather than `sicmutils.generic/*`, as manually implementing the factorial function from permute.cljc in a REPL set up as per the README works fine for n=1000. 

Is this reproducible, or due to an error in my setup?

Here is the top portion of the stack trace for (factorial 1000), up until the actual REPL call:
              Numbers.java: 1576  clojure.lang.Numbers/throwIntOverflow
              Numbers.java: 1960  clojure.lang.Numbers/multiply
              Numbers.java:  501  clojure.lang.Numbers$LongOps/multiply
              Numbers.java:  173  clojure.lang.Numbers/multiply
                  core.clj: 1018  clojure.core/*
                  core.clj: 1010  clojure.core/*
            LongRange.java:  316  clojure.lang.LongRange$LongChunk/reduce
                  core.clj:  944  clojure.core/reduce1
                  core.clj: 1020  clojure.core/*
                  core.clj: 1010  clojure.core/*
               RestFn.java:  142  clojure.lang.RestFn/applyTo
                  core.clj:  667  clojure.core/apply
                  core.clj:  662  clojure.core/apply
              permute.cljc:  189  sicmutils.util.permute$factorial/invokeStatic
              permute.cljc:  186  sicmutils.util.permute$factorial/invoke

**Comment by sritchie** [comment]
@swapneils this is a good catch! You've caught two problems...

The first is that I was using the non-overflow-allowing version of `*`. In Clojure, `*'` with a `'` allows overflow and is the right multiplication function to use for a calculation like this. In Clojurescript, overflows DON'T error, so I did pull in `g/*` for that case, as you suggest.

the n-choose-k computation remained very slow, which led me to discover [this more efficient algorithm](https://en.wikipedia.org/wiki/Binomial_coefficient#Computing_the_value_of_binomial_coefficients) for `number-of-combinations`.

Both of these are implemented in #442.

Here are the (fast!) results of your queries:

```clj
sicmutils.util.permute> (time (number-of-combinations 100000000 290))
"Elapsed time: 3.809 msecs"
165723707132879024123985940150800548665304800627517779390527222790045478356670492543799590984574708217750383830091873461027769078948771400867627714201577918265858206902115207219419536745821826192464466687550519801593338700598282633234597031633225923754674595892219256515604734466693844394723761463441369904152831072799562804322127389806430251690973082136522018514211632250245293632298656589276394343726342811200861849189886726012023681091290963978002732308890760697231674389335744157988431913722768104851123138392791574322278422546017203912519772672033197457980012584335574927612776855956015095270495509380762633948812791900039669706361392348266401442438775263351297622436724648878190331410205630189422038246601697638277018882462151396502057147044740893924865916921534012815612501621441741032961549845528102718546874597441072263922310926225330712555504925924569106363761629540943524933393238093451891905780246286699778015997266386957849166335396513324984284597372807906616655075070886601979862376836301540943520307051256518640217763198610180676823145279121608740856392015306099680653182257538499236136156612645195929727610517122243327309206212844492583751579074330293843479503345296778817861022083833774849995131938607934241119252799181883510173944514425136106799118921834667212045460125983775474762852544779716810200817818340617307308416822787296163620747323104491418034927138127085482389258109651636172141101853869213814640283116336206586986775003733967119087991289714566893286897616848865735033856229275123734192746759982639845310424131232408604931193142216750937922308662932441135905641032645408561740891486393631906716097392185410358405796215154375232691493359011311859846831301513369594880355323517828606301420386410560000000N

sicmutils.util.permute> (time (factorial 1000))
"Elapsed time: 2.318292 msecs"
402387260077093773543702433923003985719374864210714632543799910429938512398629020592044208486969404800479988610197196058631666872994808558901323829669944590997424504087073759918823627727188732519779505950995276120874975462497043601418278094646496291056393887437886487337119181045825783647849977012476632889835955735432513185323958463075557409114262417474349347553428646576611667797396668820291207379143853719588249808126867838374559731746136085379534524221586593201928090878297308431392844403281231558611036976801357304216168747609675871348312025478589320767169132448426236131412508780208000261683151027341827977704784635868170164365024153691398281264810213092761244896359928705114964975419909342221566832572080821333186116811553615836546984046708975602900950537616475847728421889679646244945160765353408198901385442487984959953319101723355556602139450399736280750137837615307127761926849034352625200015888535147331611702103968175921510907788019393178114194545257223865541461062892187960223838971476088506276862967146674697562911234082439208160153780889893964518263243671616762179168909779911903754031274622289988005195444414282012187361745992642956581746628302955570299024324153181617210465832036786906117260158783520751516284225540265170483304226143974286933061690897968482590125458327168226458066526769958652682272807075781391858178889652208164348344825993266043367660176999612831860788386150279465955131156552036093988180612138558600301435694527224206344631797460594682573103790084024432438465657245014402821885252470935190620929023136493273497565513958720559654228749774011413346962715422845862377387538230483865688976461927383814900140767310446640259899490222221765904339901886018566526485061799702356193897017860040811889729918311021171229845901641921068884387121855646124960798722908519296819372388642614839657382291123125024186649353143970137428531926649875337218940694281434118520158014123344828015051399694290153483077644569099073152433278288269864602789864321139083506217095002597389863554277196742822248757586765752344220207573630569498825087968928162753848863396909959826280956121450994871701244516461260379029309120889086942028510640182154399457156805941872748998094254742173582401063677404595741785160829230135358081840096996372524230560855903700624271243416909004153690105933983835777939410970027753472000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000N
```

**Comment by sritchie** [comment]
@swapneils , I'll go ahead and close this issue when this is merged to `main`. If you are using `deps.edn` you should be able to depend on the `main` branch, but if not let me know and I can cut a release in the next day or so with this fix.

If you don't need a release, I'm working on the large #361 and will wait to get that in!

**Comment by sritchie** [comment]
Okay, merged! Give it a try and feel free to re-open if you hit problems, or file new issues as you see them. Thanks for giving the library a spin, and let me know how it goes!

**Comment by swapneils** [comment]
I'm using clojars-via-leiningen at the moment, but manually implementing the modified code seems to work with no issues!

**Comment by sritchie** [comment]
Excellent, that's great news!
