### ISSUE TITLE
typo in simplify/rules.cljc

### ISSUE THREAD

**Issue by abdmed** [sicmutils/sicmutils#530]
Hello Sam 
Pardon, I don't know where to put this!
There is a typo at "https://github.com/sicmutils/sicmutils/blob/main/src/sicmutils/simplify/rules.cljc#L1113"
(cos (* (? n exact-integer>3?) ?f ??fs)) -> (cos (* (? **?**n exact-integer>3?) ?f ??fs))

**Comment by sritchie** [comment]
Wow, nice catch! I'll get this fixed up shortly.

**Comment by sritchie** [comment]
You get major points for doing a close read of the rules, especially given the hard to understand syntax! I'm impressed for sure.
