### ISSUE TITLE
typo in sicmutils.simplify.rules/expand-multiangle

### ISSUE THREAD

**Issue by abdmed** [sicmutils/sicmutils#534]
Hello Sam,
Attention, instead of correcting the typo, you added another one.

- at the line:
https://github.com/sicmutils/sicmutils/blob/f181f153f1432e9648206f903282e7cb4cdd9644/src/sicmutils/simplify/rules.cljc#L1100,
instead of '(sin (* (? n exact-integer>3?) ?f ??fs))' we must have: '(sin (* (? ?n exact-integer>3?) ?f ?? fs))'
- and on the line:
https://github.com/sicmutils/sicmutils/blob/f181f153f1432e9648206f903282e7cb4cdd9644/src/sicmutils/simplify/rules.cljc#L1112,
instead of '(cos (* (? n exact-integer>3?) ?f ??fs))' we must have: '(cos (* (? ?n exact-integer>3?) ?f ?? fs))'.

**Comment by sritchie** [comment]
It's actually fine to use any symbol you want inside of `(? <sym> <pred>)`. Think of `?n` like shorthand for `(? n)`. Of course `(? ?n)` works too, I just don't like the double question mark in cases where I'm not doing a template substitution on the right hand side.

I checked that this works and we are looking good:

```clj
sicmutils.simplify.rules> (expand-multiangle '(sin (* 4 'x 'y)))
(+
 (* (+ (* 3 (sin (* 'x 'y))) (* -4 (expt (sin (* 'x 'y)) 3))) (cos (* 'x 'y)))
 (* (+ (* 4 (expt (cos (* 'x 'y)) 3)) (* -3 (cos (* 'x 'y)))) (sin (* 'x 'y))))
```

Thanks for keeping an eye on it!
