### ISSUE TITLE
Implement g/gcd for complex numbers

### ISSUE THREAD

**Issue by sritchie** [sicmutils/sicmutils#58]
This gives us an implementation clue. We should be able to do this with an algorithm quite similar to Euclid's. This could be obvious, noting it here for later. http://mathforum.org/library/drmath/view/67068.html

Here it is from `numeric.scm` in `scmutils`, for "exact" complex numbers, ie, gaussian integers (the only thing we SHOULD be supporting!) 

We could install this now, with a precondition check that `(ish? z (round-complex z))`.

```scheme
;;; Euclid's algorithm for Exact Complex Numbers
;;;   suggested by William Throwe, to allow simplification
;;;   of rational functions with complex coefficients.

(define (round-complex z)
  (make-rectangular (round (real-part z))
		    (round (imag-part z))))

(define (gcd-complex a b)
  (cond ((zero? a) b)
        ((zero? b) a)
        (else
         (let ((q (round-complex (/ a b))))
           (gcd-complex b (- a (* q b)))))))
```

**Comment by adamhaber** [comment]
> This gives us an implementation clue. We should be able to do this with an algorithm quite similar to Euclid's. This could be obvious, noting it here for later. http://mathforum.org/library/drmath/view/67068.html

The link seems to be broken - any other reference to look at if I want to take a stab at this?

**Comment by sritchie** [comment]
@adamhaber found it! https://web.archive.org/web/20190720160400/http://mathforum.org/library/drmath/view/67068.html
