### ISSUE TITLE
integrate with infix parser library, possibly through a third "fusion" lib

### ISSUE THREAD

**Issue by sritchie** [sicmutils/sicmutils#98]
This library looks close to what we need: https://github.com/rm-hull/infix

Imagine "infix" as a front-end from `sicmutils`. Probably not worth adding every idea here as a dependency, but as a third-party wrapper over both this would be great.

**Comment by littleredcomputer** [comment]
If only we could overload the usual operators in JavaScript...

**Comment by sritchie** [comment]
@littleredcomputer just learned that this IS possible with "Paperscript" and "paper.js": http://paperjs.org/about/

Not quite native, but could go well in our arsenal of example work here.
